### ISSUE TITLE
Something went wrong fetching keys

### ISSUE THREAD

**Issue by Liang144** [Electrode-NSDI23/Electrode#1]
root@lll:~/Electrode-main# bash kernel-src-download.sh 
Using TMPDIR=/root/Electrode-main/linux-tarball-verify.t8lkVQ1kA.untrusted
Making sure we have all the necessary keys
gpg: 拉取‘autosigner@kernel.org’通过 WKD 时出现错误： 一般错误
gpg: error reading key: 一般错误
gpg: 拉取‘gregkh@kernel.org’通过 WKD 时出现错误： 一般错误
gpg: error reading key: 一般错误
gpg: 拉取‘torvalds@kernel.org’通过 WKD 时出现错误： 一般错误
gpg: error reading key: 一般错误
Something went wrong fetching keys

**Comment by YangZhou1997** [comment]
Can you let me know which OS and kernel you are using? We only tested on ubuntu20 with kernel 5.4.0 on Cloudlab machines. 

But from the error logs you pasted, it seems there is some gpg key missing in your OS/kernel.

**Comment by Liang144** [comment]
Ubuntu 20.04 LTS (GNU/Linux 5.8.0-050800-generic x86_64)

root@lll:~# uname -a
Linux lll 5.8.0-050800-generic #202008022230 SMP Sun Aug 2 22:33:21 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Do you know how to solve this problem about gpg key ?

**Comment by YangZhou1997** [comment]
Given that you are already in 5.8.0-050800-generic, can you try **not** using root to run the bash script (just as a normal user)? 

If that does not work, you may try manually downloading linux src (linux-5.8.tar.xz) and decompressing it as `linux` under the `xdp-handler/` folder. Then you can proceed to `bash kernel-src-prepare.sh` step. 

Sorry I have not encountered such issues before, not sure what is the root case...

**Comment by Liang144** [comment]
I have done preparing kernel sources, But In `./`, run `make clean` and `make PARANOID=0`, the prompt is as follows:

root@lll:~/Electrode-main# make clean
WARNING: Paranoid mode enabled
Makefile:151: bench/Rules.mk: 没有那个文件或目录
make: *** 没有规则可制作目标“bench/Rules.mk”。 停止。

**Comment by YangZhou1997** [comment]
Thanks for pointing it out! I just added the bench folder (it seems I missed that folder when releasing the code...)
