### ISSUE TITLE
some bugs when running the code

### ISSUE THREAD

**Issue by xinchen-jzx** [Electrode-NSDI23/Electrode#2]
hi, i am learning the projects. But i have some problems when running the code. 
➜  xdp-handler git:(master)   sudo ./fast ens1f1np1
progname: fastPaxos
progname: HandlePrepare
progname: HandlePrepareOK
progname: HandleRequest
progname: WriteBuffer
progname: PrepareFastReply
progname: FastBroadCast
libbpf: failed to pin program: File exists
Error: Failed to pin program 'FastBroadCast' to path /sys/fs/bpf/FastBroadCast
BPF program 'FastBroadCast' already pinned, unpinning it to reload it
fast: fast_user.c:319: main: Assertion `bpf_obj_pin(map_prepare_buffer_fd, "/sys/fs/bpf/paxos_prepare_buffer") == 0' failed.
[1]    16715 IOT instruction  sudo ./fast ens1f1np1

**Comment by HJPFHMATRIX** [comment]
Hello, I get an error that is similar to yours, would you mind sharing your solution?Thanks
